### ISSUE TITLE
Error: "Pywb Error  local variable 'rw_mod' referenced before assignment"

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#191]
http://p27.arquivo.pt/pywb/replay/20130124050922/http://www.dn.pt/especiais/interior.aspx?content_id=2643146&especial=Euro%272012&seccao=DESPORTO

Click on: http://www.lojadojornal.pt/LojaDoJornal/pages/homepage.xhtml

Leads to:
http://p27.arquivo.pt/pywb/replay/20131107025530/http://www.lojadojornal.pt/LojaDoJornal/pages/homepage.xhtml

Error message:
"Pywb Error

local variable 'rw_mod' referenced before assignment
Error Details:

Traceback (most recent call last):
  File "/root/src/pywb/pywb/framework/wsgi_wrappers.py", line 62, in handle_methods
    response = wb_router(env)
  File "/root/src/pywb/pywb/framework/archivalrouter.py", line 43, in **call**
    return route.handler(wbrequest)
  File "/root/src/pywb/pywb/webapp/handlers.py", line 87, in **call**
    return self.handle_request(wbrequest)
  File "/root/src/pywb/pywb/webapp/handlers.py", line 154, in handle_request
    return self.handle_replay(wbrequest, cdx_lines)
  File "/root/src/pywb/pywb/webapp/handlers.py", line 168, in handle_replay
    cdx_callback)
  File "/root/src/pywb/pywb/webapp/replay_views.py", line 91, in render_content
    failed_files)
  File "/root/src/pywb/pywb/webapp/replay_views.py", line 124, in cached_replay_capture
    return get_capture()
  File "/root/src/pywb/pywb/webapp/replay_views.py", line 116, in get_capture
    failed_files)
  File "/root/src/pywb/pywb/webapp/replay_views.py", line 193, in replay_capture
    max_size)
  File "/root/src/pywb/pywb/webapp/replay_views.py", line 226, in buffered_response
    for buff in iterator:
  File "/root/src/pywb/pywb/rewrite/rewrite_content.py", line 336, in rewrite_text_stream_to_gen
    buff = rewrite_func(buff)
  File "/root/src/pywb/pywb/rewrite/html_rewriter.py", line 365, in rewrite
    self.feed(string)
  File "/root/src/pywb/pywb/rewrite/html_rewriter.py", line 415, in feed
    HTMLParser.feed(self, string)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 325, in parse_starttag
    self.handle_startendtag(tag, attrs)
  File "/root/src/pywb/pywb/rewrite/html_rewriter.py", line 449, in handle_startendtag
    self._rewrite_tag_attrs(tag, attrs)
  File "/root/src/pywb/pywb/rewrite/html_rewriter.py", line 298, in _rewrite_tag_attrs
    attr_value = self._rewrite_url(attr_value, rw_mod)"

**Comment by Fernando-Melo** [comment]
Can't reproduce this bug. It seems to be working in arquivo.pt
By the way you will never see a python trace such as that in production, instead you will see an error html page.

**Comment by Fernando-Melo** [comment]
It is working in production
